package com.nobodyknows.chatlayoutview.CONSTANT;

public enum  MessageType {
    IMAGE, //UPLOAD REMAING
    GIF, //DONE
    VIDEO, //UPLOAD REMAING
    AUDIO, //UPLOAD AND VIEW REMAING
    RECORDING, //UPLOAD AND VIEW REMAING
    TEXT, //DONE
    DOCUMENT, //UPLOAD AND VIEW REMAING
    MAP,
    CONTACT,
    CUSTOM,
    DATE, //DONE
    STICKER, //DONE
    REPLY_MESSAGE
}
